
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.StyleCop.Gui.OptionPanelWidgets
{
	public partial class SpellingOptionsPanelWidget
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label11;

		private global::Gtk.Table table3;

		private global::Gtk.Button addRecognizedWordButton;

		private global::Gtk.Entry addRecognizedWordEntry;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView recognizedWordsNodeView;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Button removeRecognizedWordButton;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label14;

		private global::Gtk.Table table1;

		private global::Gtk.Entry addAlternateWordEntry;

		private global::Gtk.Button addDeprecatedWordButton;

		private global::Gtk.Entry addDeprecatedWordEntry;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView deprecatedWordsNodeView;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Button removeDeprecatedWordButton;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Table table2;

		private global::Gtk.Button addFolderButton;

		private global::Gtk.Entry addFolderEntry;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.NodeView foldersNodeView;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Button removeFolderButton;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label GtkLabel8;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MonoDevelop.StyleCop.Gui.OptionPanelWidgets.SpellingOptionsPanelWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 625;
			this.HeightRequest = 495;
			this.Name = "MonoDevelop.StyleCop.Gui.OptionPanelWidgets.SpellingOptionsPanelWidget";
			// Container child MonoDevelop.StyleCop.Gui.OptionPanelWidgets.SpellingOptionsPanelWidget.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Any words in the following list will not be reported as spelling mistakes. Add wo" +
					"rds to this list if they should be ignored by spelling rules.");
			this.label11.Wrap = true;
			this.label11.Justify = ((global::Gtk.Justification)(3));
			this.label11.WidthChars = 80;
			this.vbox7.Add(this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.addRecognizedWordButton = new global::Gtk.Button();
			this.addRecognizedWordButton.CanFocus = true;
			this.addRecognizedWordButton.Name = "addRecognizedWordButton";
			this.addRecognizedWordButton.UseUnderline = true;
			this.addRecognizedWordButton.Label = global::Mono.Unix.Catalog.GetString("Add");
			this.table3.Add(this.addRecognizedWordButton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.addRecognizedWordButton]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table3.Gtk.Table+TableChild
			this.addRecognizedWordEntry = new global::Gtk.Entry();
			this.addRecognizedWordEntry.CanFocus = true;
			this.addRecognizedWordEntry.Name = "addRecognizedWordEntry";
			this.addRecognizedWordEntry.IsEditable = true;
			this.addRecognizedWordEntry.InvisibleChar = '●';
			this.table3.Add(this.addRecognizedWordEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.addRecognizedWordEntry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.recognizedWordsNodeView = new global::Gtk.NodeView();
			this.recognizedWordsNodeView.CanFocus = true;
			this.recognizedWordsNodeView.Name = "recognizedWordsNodeView";
			this.GtkScrolledWindow.Add(this.recognizedWordsNodeView);
			this.table3.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Recognized words:");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Recognized word to add:");
			this.table3.Add(this.label8);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.label8]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.removeRecognizedWordButton = new global::Gtk.Button();
			this.removeRecognizedWordButton.CanFocus = true;
			this.removeRecognizedWordButton.Name = "removeRecognizedWordButton";
			this.removeRecognizedWordButton.UseUnderline = true;
			this.removeRecognizedWordButton.Label = global::Mono.Unix.Catalog.GetString("Remove");
			this.vbox4.Add(this.removeRecognizedWordButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.removeRecognizedWordButton]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.vbox4.Add(this.fixed4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fixed4]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table3.Add(this.vbox4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.vbox4]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add(this.table3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.table3]));
			w11.Position = 1;
			this.GtkAlignment.Add(this.vbox7);
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Recognized Words</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox6.Add(this.frame1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame1]));
			w14.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Any words in the following list will not be reported as spelling mistakes. Add wo" +
					"rds to this list so that spelling suggestions may be made.");
			this.label14.Wrap = true;
			this.label14.Justify = ((global::Gtk.Justification)(3));
			this.label14.WidthChars = 80;
			this.vbox9.Add(this.label14);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label14]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.addAlternateWordEntry = new global::Gtk.Entry();
			this.addAlternateWordEntry.CanFocus = true;
			this.addAlternateWordEntry.Name = "addAlternateWordEntry";
			this.addAlternateWordEntry.IsEditable = true;
			this.addAlternateWordEntry.InvisibleChar = '●';
			this.table1.Add(this.addAlternateWordEntry);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.addAlternateWordEntry]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.addDeprecatedWordButton = new global::Gtk.Button();
			this.addDeprecatedWordButton.CanFocus = true;
			this.addDeprecatedWordButton.Name = "addDeprecatedWordButton";
			this.addDeprecatedWordButton.UseUnderline = true;
			this.addDeprecatedWordButton.Label = global::Mono.Unix.Catalog.GetString("Add");
			this.table1.Add(this.addDeprecatedWordButton);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.addDeprecatedWordButton]));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.addDeprecatedWordEntry = new global::Gtk.Entry();
			this.addDeprecatedWordEntry.CanFocus = true;
			this.addDeprecatedWordEntry.Name = "addDeprecatedWordEntry";
			this.addDeprecatedWordEntry.IsEditable = true;
			this.addDeprecatedWordEntry.InvisibleChar = '●';
			this.table1.Add(this.addDeprecatedWordEntry);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.addDeprecatedWordEntry]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table1.Add(this.fixed2);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.fixed2]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.deprecatedWordsNodeView = new global::Gtk.NodeView();
			this.deprecatedWordsNodeView.CanFocus = true;
			this.deprecatedWordsNodeView.Name = "deprecatedWordsNodeView";
			this.GtkScrolledWindow1.Add(this.deprecatedWordsNodeView);
			this.table1.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow1]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Deprecated word to add:");
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Alternative word:");
			this.table1.Add(this.label5);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Deprecated word,\nalternative word:");
			this.table1.Add(this.label6);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.removeDeprecatedWordButton = new global::Gtk.Button();
			this.removeDeprecatedWordButton.CanFocus = true;
			this.removeDeprecatedWordButton.Name = "removeDeprecatedWordButton";
			this.removeDeprecatedWordButton.UseUnderline = true;
			this.removeDeprecatedWordButton.Label = global::Mono.Unix.Catalog.GetString("Remove");
			this.vbox3.Add(this.removeDeprecatedWordButton);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.removeDeprecatedWordButton]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.vbox3.Add(this.fixed3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed3]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.table1.Add(this.vbox3);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.vbox3]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox9.Add(this.table1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.table1]));
			w28.Position = 1;
			this.GtkAlignment1.Add(this.vbox9);
			this.frame2.Add(this.GtkAlignment1);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Deprecated Words</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel5;
			this.vbox6.Add(this.frame2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame2]));
			w31.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Any folders in the following list will be searched for CustomDictionary files.");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.addFolderButton = new global::Gtk.Button();
			this.addFolderButton.CanFocus = true;
			this.addFolderButton.Name = "addFolderButton";
			this.addFolderButton.UseUnderline = true;
			this.addFolderButton.Label = global::Mono.Unix.Catalog.GetString("Add");
			this.table2.Add(this.addFolderButton);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2[this.addFolderButton]));
			w33.LeftAttach = ((uint)(2));
			w33.RightAttach = ((uint)(3));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.addFolderEntry = new global::Gtk.Entry();
			this.addFolderEntry.CanFocus = true;
			this.addFolderEntry.Name = "addFolderEntry";
			this.addFolderEntry.IsEditable = true;
			this.addFolderEntry.InvisibleChar = '●';
			this.table2.Add(this.addFolderEntry);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2[this.addFolderEntry]));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.foldersNodeView = new global::Gtk.NodeView();
			this.foldersNodeView.CanFocus = true;
			this.foldersNodeView.Name = "foldersNodeView";
			this.GtkScrolledWindow2.Add(this.foldersNodeView);
			this.table2.Add(this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2[this.GtkScrolledWindow2]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Dictionary folder to add:");
			this.table2.Add(this.label2);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2[this.label2]));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Dictionary folders:");
			this.table2.Add(this.label3);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2[this.label3]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.removeFolderButton = new global::Gtk.Button();
			this.removeFolderButton.CanFocus = true;
			this.removeFolderButton.Name = "removeFolderButton";
			this.removeFolderButton.UseUnderline = true;
			this.removeFolderButton.Label = global::Mono.Unix.Catalog.GetString("Remove");
			this.vbox2.Add(this.removeFolderButton);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.removeFolderButton]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox2.Add(this.fixed1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed1]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.table2.Add(this.vbox2);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox2]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.LeftAttach = ((uint)(2));
			w41.RightAttach = ((uint)(3));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table2]));
			w42.Position = 1;
			this.GtkAlignment2.Add(this.vbox1);
			this.frame3.Add(this.GtkAlignment2);
			this.GtkLabel8 = new global::Gtk.Label();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Dictionary Folders</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel8;
			this.vbox6.Add(this.frame3);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame3]));
			w45.Position = 2;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.removeRecognizedWordButton.Clicked += new global::System.EventHandler(this.RemoveRecognizedWordButtonClicked);
			this.addRecognizedWordEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.AddRecognizedWordEntryReleaseEvent);
			this.addRecognizedWordButton.Clicked += new global::System.EventHandler(this.AddRecognizedWordButtonClicked);
			this.removeDeprecatedWordButton.Clicked += new global::System.EventHandler(this.RemoveDeprecatedWordButtonClicked);
			this.addDeprecatedWordEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.AddDeprecatedWordEntryReleaseEvent);
			this.addDeprecatedWordButton.Clicked += new global::System.EventHandler(this.AddDeprecatedWordButtonClicked);
			this.addAlternateWordEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.AddAlternateWordEntryReleaseEvent);
			this.removeFolderButton.Clicked += new global::System.EventHandler(this.RemoveFolderButtonClicked);
			this.addFolderEntry.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.AddFolderEntryReleaseEvent);
			this.addFolderButton.Clicked += new global::System.EventHandler(this.AddFolderButtonClicked);
		}
	}
}
