
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.StyleCop
{
	internal partial class ValidPrefixesOptionsPanel
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label6;
		private global::Gtk.Fixed fixed8;
		private global::Gtk.Table table5;
		private global::Gtk.Button addPrefixButton;
		private global::Gtk.Entry addPrefixEntry;
		private global::Gtk.Fixed fixed10;
		private global::Gtk.Fixed fixed11;
		private global::Gtk.Fixed fixed12;
		private global::Gtk.Fixed fixed14;
		private global::Gtk.Fixed fixed6;
		private global::Gtk.Fixed fixed7;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView prefixNodeView;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button removePrefixButton;
		private global::Gtk.Fixed fixed13;
		private global::Gtk.Fixed fixed9;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.StyleCop.ValidPrefixesOptionsPanel
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 625;
			this.HeightRequest = 495;
			this.Name = "MonoDevelop.StyleCop.ValidPrefixesOptionsPanel";
			// Container child MonoDevelop.StyleCop.ValidPrefixesOptionsPanel.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Any one or two character prefix not included in the following list will be consid" +
			"ered to be invalid Hungarian notation. Add prefixes to this list if they should " +
			"be ignored by Hungarian notation rules.");
			this.label6.Wrap = true;
			this.label6.Justify = ((global::Gtk.Justification)(3));
			this.label6.WidthChars = 80;
			this.vbox4.Add (this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed ();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.vbox4.Add (this.fixed8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed8]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.addPrefixButton = new global::Gtk.Button ();
			this.addPrefixButton.CanFocus = true;
			this.addPrefixButton.Name = "addPrefixButton";
			this.addPrefixButton.UseUnderline = true;
			this.addPrefixButton.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.table5.Add (this.addPrefixButton);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5 [this.addPrefixButton]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table5.Gtk.Table+TableChild
			this.addPrefixEntry = new global::Gtk.Entry ();
			this.addPrefixEntry.CanFocus = true;
			this.addPrefixEntry.Name = "addPrefixEntry";
			this.addPrefixEntry.IsEditable = true;
			this.addPrefixEntry.InvisibleChar = '●';
			this.table5.Add (this.addPrefixEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table5 [this.addPrefixEntry]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.table5.Add (this.fixed10);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed10]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(0));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.table5.Add (this.fixed11);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed11]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(1));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed12 = new global::Gtk.Fixed ();
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			this.table5.Add (this.fixed12);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed12]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed14 = new global::Gtk.Fixed ();
			this.fixed14.Name = "fixed14";
			this.fixed14.HasWindow = false;
			this.table5.Add (this.fixed14);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed14]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.table5.Add (this.fixed6);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed6]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(0));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.table5.Add (this.fixed7);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed7]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(0));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.prefixNodeView = new global::Gtk.NodeView ();
			this.prefixNodeView.CanFocus = true;
			this.prefixNodeView.Name = "prefixNodeView";
			this.GtkScrolledWindow.Add (this.prefixNodeView);
			this.table5.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5 [this.GtkScrolledWindow]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter a one or two character prefix to add:");
			this.table5.Add (this.label3);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table5 [this.label3]));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Currently excluded prefixes:");
			this.table5.Add (this.label4);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table5 [this.label4]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.removePrefixButton = new global::Gtk.Button ();
			this.removePrefixButton.CanFocus = true;
			this.removePrefixButton.Name = "removePrefixButton";
			this.removePrefixButton.UseUnderline = true;
			this.removePrefixButton.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.vbox3.Add (this.removePrefixButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.removePrefixButton]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed13 = new global::Gtk.Fixed ();
			this.fixed13.Name = "fixed13";
			this.fixed13.HasWindow = false;
			this.vbox3.Add (this.fixed13);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed13]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.table5.Add (this.vbox3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table5 [this.vbox3]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table5]));
			w18.Position = 2;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed ();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.vbox4.Add (this.fixed9);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed9]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
