
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.StyleCop.Gui.OptionPanelWidgets
{
	public partial class RulesOptionsPanelWidget
	{
		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Entry entry9;

		private global::Gtk.Button button10;

		private global::Gtk.Table table3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView detailedSettingsNodeView;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView rulesTreeView;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Fixed fixed18;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView descriptionTextView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MonoDevelop.StyleCop.Gui.OptionPanelWidgets.RulesOptionsPanelWidget
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 625;
			this.HeightRequest = 495;
			this.Name = "MonoDevelop.StyleCop.Gui.OptionPanelWidgets.RulesOptionsPanelWidget";
			// Container child MonoDevelop.StyleCop.Gui.OptionPanelWidgets.RulesOptionsPanelWidget.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Choose which rules to run on this project.");
			this.hbox13.Add(this.label20);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label20]));
			w1.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 1F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Find");
			this.hbox13.Add(this.label21);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label21]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.hbox13.Add(this.entry9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.entry9]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Go");
			this.hbox13.Add(this.button10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button10]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox10.Add(this.hbox13);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox13]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.detailedSettingsNodeView = new global::Gtk.NodeView();
			this.detailedSettingsNodeView.CanFocus = true;
			this.detailedSettingsNodeView.Name = "detailedSettingsNodeView";
			this.GtkScrolledWindow1.Add(this.detailedSettingsNodeView);
			this.table3.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow1]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.rulesTreeView = new global::Gtk.TreeView();
			this.rulesTreeView.CanFocus = true;
			this.rulesTreeView.Name = "rulesTreeView";
			this.GtkScrolledWindow2.Add(this.rulesTreeView);
			this.table3.Add(this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow2]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Detailed settings");
			this.table3.Add(this.label18);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.label18]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Enabled rules");
			this.table3.Add(this.label19);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3[this.label19]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox10.Add(this.table3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.table3]));
			w12.Position = 1;
			// Container child vbox10.Gtk.Box+BoxChild
			this.fixed18 = new global::Gtk.Fixed();
			this.fixed18.Name = "fixed18";
			this.fixed18.HasWindow = false;
			this.vbox10.Add(this.fixed18);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.fixed18]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.HeightRequest = 100;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.descriptionTextView = new global::Gtk.TextView();
			this.descriptionTextView.CanFocus = true;
			this.descriptionTextView.Name = "descriptionTextView";
			this.GtkScrolledWindow.Add(this.descriptionTextView);
			this.vbox10.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow]));
			w15.Position = 3;
			w15.Expand = false;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
